/**
 * SPDX-FileCopyrightText: 2025-2026 Iuri Suzano <iuri@astware.bar>
 * SPDX-License-Identifier: MIT
 *
 * Application startup and lifecycle entry point.
 */

/* Application entry point and GTK application lifecycle. */

#include <adwaita.h>
#include <gtk/gtk.h>
#include <gdk/gdk.h>
#include <gio/gio.h>
#include <locale.h>
#include <stdio.h>
#include <stdarg.h>

#include "lds_terminal.h"
#include "internal/diag.h"
#include "internal/diag_runtime.h"
#include "internal/app_args.h"
#include "internal/app_actions.h"
#include "internal/app_runtime.h"
#include "internal/lds_terminal_internal.h"

/* GResource symbol generated by Meson from data/lds-terminal.gresource.xml. */
extern GResource *lds_terminal_get_resource(void);

typedef struct _LdsTerminalRuntime LdsTerminalRuntime;

static void lds_terminal_register_resources(LdsTerminalState *state);
static void lds_terminal_on_startup(GApplication *app, gpointer user_data);
static void lds_terminal_install_log_filters(void);
static GLogWriterOutput lds_terminal_log_writer_filter(GLogLevelFlags log_level,
													   const GLogField *fields, gsize n_fields,
													   gpointer user_data);
static void lds_terminal_command_args_clear(LdsTerminalCommandArgs *args);
static int lds_terminal_fail(int code, const char *fmt, ...) G_GNUC_WARN_UNUSED_RESULT;
static int lds_terminal_main_teardown(LdsTerminalRuntime *runtime, int status);
static void lds_terminal_local_on_window_destroy(GtkWidget *widget, gpointer user_data);
static const char *lds_terminal_diag_stage_name(gint stage);

typedef struct _LdsTerminalRuntime {
	LdsTerminalState *state;
	LdsTerminalDiagRuntime diag;
	int activate_failure_exit_code;
} LdsTerminalRuntime;

enum {
	DIAG_STAGE_BOOT = 0,
	DIAG_STAGE_ARGS_PARSED,
	DIAG_STAGE_APP_CREATED,
	DIAG_STAGE_RUN_ENTER,
	DIAG_STAGE_STARTUP_BEGIN,
	DIAG_STAGE_STARTUP_END,
	DIAG_STAGE_ACTIVATE_BEGIN,
	DIAG_STAGE_ACTIVATE_END,
	DIAG_STAGE_RUN_EXIT
};

enum {
	LDS_TERMINAL_EXIT_OK = 0,
	LDS_TERMINAL_EXIT_ARG_ERROR = 2,
	LDS_TERMINAL_EXIT_INIT_ERROR = 3
};

/* GTK application activation handler. */
static void lds_terminal_on_activate(GtkApplication *app, gpointer user_data) {
	LdsTerminalRuntime *runtime = user_data;
	if (!runtime || !runtime->state)
		return;

	LdsTerminalState *state = runtime->state;
	lds_terminal_diag_runtime_set_stage(&runtime->diag, DIAG_STAGE_ACTIVATE_BEGIN);
	lds_terminal_diag_log("main", "activate begin");

	lds_terminal_register_resources(state);

	if (!state->windows)
		state->windows = g_ptr_array_new();

	if (!lds_terminal_create(state, &state->args)) {
		int exit_code = lds_terminal_fail(LDS_TERMINAL_EXIT_INIT_ERROR,
										  "failed to create initial terminal window");
		if (runtime->activate_failure_exit_code == 0) {
			runtime->activate_failure_exit_code = exit_code;
			lds_terminal_diag_log("main", "activate first failure fixed code=%d", exit_code);
		}
		lds_terminal_diag_log("main", "activate failed code=%d", exit_code);
		g_application_quit(G_APPLICATION(app));
		return;
	}

	lds_terminal_diag_runtime_set_stage(&runtime->diag, DIAG_STAGE_ACTIVATE_END);
	lds_terminal_diag_log("main", "activate end");
}

static void lds_terminal_on_startup(GApplication *app, gpointer user_data) {
	LdsTerminalRuntime *runtime = user_data;
	if (!runtime)
		return;

	lds_terminal_diag_runtime_set_stage(&runtime->diag, DIAG_STAGE_STARTUP_BEGIN);
	lds_terminal_diag_log("main", "startup begin");
	lds_terminal_app_configure_accelerators(GTK_APPLICATION(app));

	lds_terminal_diag_runtime_set_stage(&runtime->diag, DIAG_STAGE_STARTUP_END);
	lds_terminal_diag_log("main", "startup end");
}

/* Register embedded resources and icons once. */
static void lds_terminal_register_resources(LdsTerminalState *state) {
	(void)state;
	static gsize resources_once = 0;
	static GdkDisplay *icon_path_display = NULL;

	if (g_once_init_enter(&resources_once)) {
		g_resources_register(lds_terminal_get_resource());
		gtk_window_set_default_icon_name("lds-terminal");
		g_once_init_leave(&resources_once, 1);
		lds_terminal_diag_log("main", "resources registered");
	}

	/* Icon theme path depends on an initialized display; register when available. */
	GdkDisplay *display = gdk_display_get_default();
	if (display && display != icon_path_display) {
		gtk_icon_theme_add_resource_path(gtk_icon_theme_get_for_display(display),
										 "/bar/astware/lds-terminal");
		icon_path_display = display;
		lds_terminal_diag_log("main", "icon theme resource path registered");
	}
}

static void lds_terminal_install_log_filters(void) {
	/* Process-wide GLib writer: install once during early boot.
	 * GTK emits this non-fatal warning via structured logging on some stacks.
	 * Filter only targeted messages and keep all other logs unchanged. */
	g_log_set_writer_func(lds_terminal_log_writer_filter, NULL, NULL);
}

static GLogWriterOutput lds_terminal_log_writer_filter(GLogLevelFlags log_level,
													   const GLogField *fields, gsize n_fields,
													   gpointer user_data) {
	(void)user_data;

	if ((log_level & G_LOG_LEVEL_WARNING) != 0 && fields) {
		const gchar *domain = NULL;
		const gchar *message = NULL;
		for (gsize i = 0; i < n_fields; i++) {
			if (g_strcmp0(fields[i].key, "GLIB_DOMAIN") == 0)
				domain = (const gchar *)fields[i].value;
			else if (g_strcmp0(fields[i].key, "MESSAGE") == 0)
				message = (const gchar *)fields[i].value;
		}
		if (g_strcmp0(domain, "Gtk") == 0 && message &&
			g_str_has_prefix(message, "Broken accounting of active state for widget "))
			return G_LOG_WRITER_HANDLED;
		if (g_strcmp0(domain, "Gdk") == 0 && message &&
			g_str_has_prefix(message,
							 "Cannot get portal org.freedesktop.portal.Screenshot version:"))
			return G_LOG_WRITER_HANDLED;
	}

	return g_log_writer_default(log_level, fields, n_fields, user_data);
}

/* Program entry point. */
int main(int argc, char **argv) {
	int status = LDS_TERMINAL_EXIT_OK;
	g_autoptr(GError) parse_error = NULL;
	LdsTerminalRuntime runtime = {0};

	setlocale(LC_ALL, "");

	LdsTerminalState *state = g_new0(LdsTerminalState, 1);
	runtime.state = state;
	lds_terminal_diag_runtime_init(&runtime.diag);

	lds_terminal_diag_init();
	lds_terminal_diag_runtime_install_glib_log_capture(&runtime.diag);
	lds_terminal_install_log_filters();
	lds_terminal_diag_runtime_set_stage(&runtime.diag, DIAG_STAGE_BOOT);
	lds_terminal_diag_log("main", "process start argc=%d", argc);
	const char *display = g_getenv("DISPLAY");
	const char *xdg_session_type = g_getenv("XDG_SESSION_TYPE");
	const char *dbus_session_bus_address = g_getenv("DBUS_SESSION_BUS_ADDRESS");
	const char *xdg_runtime_dir = g_getenv("XDG_RUNTIME_DIR");
	lds_terminal_diag_log("env", "DISPLAY=%s", display ? display : "(null)");
	lds_terminal_diag_log("env", "XDG_SESSION_TYPE=%s",
						  xdg_session_type ? xdg_session_type : "(null)");
	lds_terminal_diag_log("env", "DBUS_SESSION_BUS_ADDRESS=%s",
						  dbus_session_bus_address ? dbus_session_bus_address : "(null)");
	lds_terminal_diag_log("env", "XDG_RUNTIME_DIR=%s",
						  xdg_runtime_dir ? xdg_runtime_dir : "(null)");

	lds_terminal_diag_runtime_start_watchdog(&runtime.diag, lds_terminal_diag_stage_name);

	if (!lds_terminal_parse_args(state, &argc, &argv, &parse_error)) {
		lds_terminal_diag_log("main", "argument parsing failed");
		int exit_code =
			lds_terminal_fail(LDS_TERMINAL_EXIT_ARG_ERROR, "argument parsing failed: %s",
							  parse_error ? parse_error->message : "unknown error");
		return lds_terminal_main_teardown(&runtime, exit_code);
	}
	lds_terminal_diag_runtime_set_stage(&runtime.diag, DIAG_STAGE_ARGS_PARSED);
	lds_terminal_diag_log("main", "argument parsing ok");
	lds_terminal_runtime_bootstrap_environment(state);
	gboolean use_gapplication = lds_terminal_runtime_use_gapplication();
	lds_terminal_diag_log("main", "runtime mode=%s",
						  use_gapplication ? "gapplication" : "local-compat");

	if (!use_gapplication) {
		/* Local mode is a compatibility/debug path that bypasses GtkApplication lifecycle. */
		lds_terminal_diag_log("main", "local mode enabled");
		gtk_init();
		adw_init();
		lds_terminal_register_resources(state);

		if (!state->windows)
			state->windows = g_ptr_array_new();

		LdsTerminal *terminal = lds_terminal_create(state, &state->args);
		if (!terminal || !terminal->window) {
			lds_terminal_diag_log("main", "local mode failed to create window");
			int exit_code = lds_terminal_fail(LDS_TERMINAL_EXIT_INIT_ERROR,
											  "local mode failed to create window");
			if (terminal)
				lds_terminal_destroy(terminal);
			return lds_terminal_main_teardown(&runtime, exit_code);
		}

		g_autoptr(GMainLoop) loop = g_main_loop_new(NULL, FALSE);
		g_signal_connect(terminal->window, "destroy",
						 G_CALLBACK(lds_terminal_local_on_window_destroy), loop);
		lds_terminal_diag_log("main", "local loop enter");
		g_main_loop_run(loop);
		lds_terminal_diag_log("main", "local loop exit");
		return lds_terminal_main_teardown(&runtime, LDS_TERMINAL_EXIT_OK);
	}

	GApplicationFlags flags = G_APPLICATION_DEFAULT_FLAGS;

	if (state->args.no_remote)
		flags |= G_APPLICATION_NON_UNIQUE;

	g_autoptr(AdwApplication) app = adw_application_new("bar.astware.lds-terminal", flags);
	state->app = GTK_APPLICATION(app);
	lds_terminal_diag_runtime_set_stage(&runtime.diag, DIAG_STAGE_APP_CREATED);
	lds_terminal_diag_log("main", "application created flags=%u", (guint)flags);

	g_signal_connect(app, "activate", G_CALLBACK(lds_terminal_on_activate), &runtime);
	g_signal_connect(app, "startup", G_CALLBACK(lds_terminal_on_startup), &runtime);

	lds_terminal_diag_runtime_set_stage(&runtime.diag, DIAG_STAGE_RUN_ENTER);
	lds_terminal_diag_log("main", "g_application_run enter");
	status = g_application_run(G_APPLICATION(app), argc, argv);
	lds_terminal_diag_runtime_set_stage(&runtime.diag, DIAG_STAGE_RUN_EXIT);
	if (status == LDS_TERMINAL_EXIT_OK && runtime.activate_failure_exit_code != 0)
		status = runtime.activate_failure_exit_code;
	lds_terminal_diag_log("main", "g_application_run exit status=%d", status);
	return lds_terminal_main_teardown(&runtime, status);
}

static void lds_terminal_command_args_clear(LdsTerminalCommandArgs *args) {
	if (!args)
		return;

	g_free(args->executable);
	g_strfreev(args->command);
	g_free(args->working_directory);
	g_free(args->title);
	g_free(args->tabs);
	g_free(args->profile);

	*args = (LdsTerminalCommandArgs){0};
}

static int lds_terminal_fail(int code, const char *fmt, ...) {
	va_list ap;
	va_start(ap, fmt);
	g_autofree gchar *msg = g_strdup_vprintf(fmt, ap);
	va_end(ap);

	g_printerr("lds-terminal error[%d]: %s\n", code, msg ? msg : "unknown error");
	lds_terminal_diag_log("error", "code=%d message=%s", code, msg ? msg : "unknown error");

	return code;
}

static int lds_terminal_main_teardown(LdsTerminalRuntime *runtime, int status) {
	if (!runtime)
		return status;

	if (runtime->state && runtime->state->windows) {
		/* Ensure full window teardown if any entries remain in global state. */
		while (runtime->state->windows->len > 0) {
			guint len_before = runtime->state->windows->len;
			LdsTerminal *terminal = g_ptr_array_index(runtime->state->windows, 0);
			if (terminal)
				lds_terminal_destroy(terminal);

			/* Defensive progress guard: never spin forever on inconsistent ownership. */
			if (runtime->state->windows->len == len_before)
				g_ptr_array_remove_index(runtime->state->windows, 0);
		}
		g_ptr_array_free(runtime->state->windows, FALSE);
	}

	if (runtime->state)
		lds_terminal_command_args_clear(&runtime->state->args);

	g_free(runtime->state);
	runtime->state = NULL;

	lds_terminal_diag_runtime_release(&runtime->diag);
	lds_terminal_diag_shutdown();

	return status;
}

static void lds_terminal_local_on_window_destroy(GtkWidget *widget, gpointer user_data) {
	(void)widget;

	GMainLoop *loop = user_data;
	if (loop && g_main_loop_is_running(loop))
		g_main_loop_quit(loop);
}

static const char *lds_terminal_diag_stage_name(gint stage) {
	switch (stage) {
	case DIAG_STAGE_BOOT:
		return "boot";
	case DIAG_STAGE_ARGS_PARSED:
		return "args_parsed";
	case DIAG_STAGE_APP_CREATED:
		return "app_created";
	case DIAG_STAGE_RUN_ENTER:
		return "run_enter";
	case DIAG_STAGE_STARTUP_BEGIN:
		return "startup_begin";
	case DIAG_STAGE_STARTUP_END:
		return "startup_end";
	case DIAG_STAGE_ACTIVATE_BEGIN:
		return "activate_begin";
	case DIAG_STAGE_ACTIVATE_END:
		return "activate_end";
	case DIAG_STAGE_RUN_EXIT:
		return "run_exit";
	default:
		return "unknown";
	}
}
